(function(d,b){b.FormController=can.Control.extend({},{id:null,element:null,optionControllers:{},settings:{},dependencies:{},optionsContainer:"options",init:function(a,c){this.element=a;this.settings=c;this.id=b.Vars.attrs.id;this.setOptionControllers();this.updateOptionControllers();this.showAllDependencies()},setOptionControllers:function(){var a=this,c=a.element.find(".mpsl-option"),b={showErrorType:this.settings.showErrorType};d.each(c,function(c,g){var k=a.createOptionController(d(g),b),l=k.getName();
a.optionControllers[l]=k})},updateOptionControllers:function(){var a=this;d.each(b.Vars[this.optionsContainer],function(c,b){d.each(b.options,function(c,b){b.hasOwnProperty("actions")&&d.each(b.actions,function(b,e){a.optionControllers[c].addAction(b,e)});b.hasOwnProperty("helpers")&&d.each(b.helpers,function(b,e){a.optionControllers[c].addHelper(e,a.optionControllers[e])})})})},createOptionController:function(a,c){var e;e=a.attr("data-mpsl-option-type");var f=a.hasClass("mpsl-nested-option"),g="";
f&&(g=a.attr("data-parent-name"),g=this.optionControllers[g]);d.extend(c,{isNested:f,parentOption:f?g:{}});switch(e){case "text":e=new b.TextControl(d(a),c);break;case "number":e=new b.NumberControl(d(a),c);break;case "textarea":e=new b.TextareaControl(d(a),c);break;case "checkbox":e=new b.CheckboxControl(d(a),c);break;case "select":e=new b.SelectControl(d(a),c);break;case "radio_group":e=new b.RadioGroupControl(d(a),c);break;case "radio_buttons":e=new b.RadioButtonsControl(d(a),c);break;case "button_group":e=
new b.ButtonGroupControl(d(a),c);break;case "action_group":e=new b.ActionGroupControl(d(a),c);break;case "library_image":e=new b.ImageLibraryControl(d(a),c);break;case "library_video":e=new b.VideoLibraryControl(d(a),c);break;case "image_url":e=new b.ImageUrlControl(d(a),c);break;case "hidden":e=new b.HiddenControl(d(a),c);break;case "alias":e=new b.AliasControl(d(a),c);break;case "shortcode":e=new b.ShortcodeControl(d(a),c);break;case "align_table":e=new b.AlignTableControl(d(a),c);break;case "datepicker":e=
new b.DatePicker(d(a),c);break;case "codemirror":e=new b.CodeMirrorControl(d(a),c);break;default:e=new b.OptionControl(d(a),c)}e.linkForm(this);f=e.getDependency();"undefined"!==typeof f&&this.addDependency(e.getName(),f);return e},addDependency:function(a,c){this.dependencies[c.parameter]||(this.dependencies[c.parameter]={});this.dependencies[c.parameter][c.value]||(this.dependencies[c.parameter][c.value]=[]);this.dependencies[c.parameter][c.value].push(a)},showDependencedOptions:function(a){var c=
this,b=!1;if(c.dependencies.hasOwnProperty(a)){var f=c.optionControllers[a],g=f.getValue();d.each(c.dependencies[a],function(a,l){a=f.fixValueType(a);d.each(l,function(l,n){var h=c.optionControllers[n];f.isOptionEnabled()?(b=d.isArray(g)?-1<d.inArray(a,g):a===g)?h.enable():h.disable():h.disable();c.showDependencedOptions(h.getName())})})}},showAllDependencies:function(){var a=this,c=!1;d.each(a.dependencies,function(b,f){var g=a.optionControllers[b],k=g.getValue();d.each(f,function(f,m){f=g.fixValueType(f);
d.each(m,function(g,h){a.optionControllers[b].isOptionEnabled()?(c=d.isArray(k)?-1<d.inArray(f,k):f===k)?a.optionControllers[h].enable():a.optionControllers[h].disable():a.optionControllers[h].disable();a.showDependencedOptions(a.optionControllers[h].getName())})})})},verifyOptions:function(){var a=!0;d.each(this.optionControllers,function(c,b){if(b.isOptionEnabled()&&!b.verifyOption())return a=!1});return a},getFormData:function(){var a={};d.each(this.optionControllers,function(c,b){var d=b.getGroupName();
"undefined"===typeof a[d]&&(a[d]={});b.isOptionEnabled()&&(a[d][c]=b.getValue())});return a},getOptionsList:function(){var a={};d.each(this.optionControllers,function(c,b){b.isOptionEnabled()&&(a[c]=b.getValue())});return a},render:function(){}});b.OptionControl=can.Control.extend({defaults:{}},{controls:[],helpers:{},actions:{},element:null,form:null,isNested:!1,parentOption:{},childOptions:{},showErrorType:"popup",init:function(a,c){this.setElement(a);this.elementWrapper=a.closest(".mpsl-option-wrapper");
this.containerType=a.closest(".mpsl_layers_wrapper").length?"layers":"options";this.name=a.attr("data-name");this.group=a.closest("[data-group]").attr("data-group");this.helpers={};this.actions={};this.isNested=c.isNested;this.parentOption=c.parentOption;this.childOptions={};this.isNested&&this.parentOption.addChild(this);c.hasOwnProperty("showErrorType")&&(this.showErrorType=c.showErrorType);"options"===this.containerType?c.isNested?this.settings=b.Vars.options[this.group].options[this.parentOption.getName()].options[this.name]:
(this.settings=b.Vars.options[this.group].options[this.name],this.isMultiValue=b.Vars.options[this.group].options[this.name].hasOwnProperty("list")):this.settings=c.isNested?b.Vars.layer_options[this.group].options[this.parentOption.getName()].options[this.name]:b.Vars.layer_options[this.group].options[this.name];this.enabled=this.valid=!0},setElement:function(a){this.element=a.find("input")},addChild:function(a){this.childOptions[a.getName()]=a},getName:function(){return this.name},getLabel:function(){return this.settings.hasOwnProperty("label")&&
this.settings.label?this.settings.label:this.settings.hasOwnProperty("label2")&&this.settings.label2?this.settings.label2:this.getName()},getDependency:function(){return this.settings.dependency},getGroupName:function(){return this.group},getValue:function(){return this.element.val()},setValue:function(a,c){this.element.val(a);"undefined"!==typeof c&&c||this.element.change()},showError:function(a){b.Functions.showMessage(a,b.Functions.MSG_ERROR_TYPE)},hideError:function(){},verifyOption:function(){return!0},
isValid:function(){return this.valid},isOptionEnabled:function(){return this.enabled},enable:function(){this.enabled=!0;this.elementWrapper.removeClass("mpsl-dependency-hide")},disable:function(){this.enabled=!1;this.elementWrapper.addClass("mpsl-dependency-hide")},linkForm:function(a){this.form=a},addHelper:function(a,c){this.helpers[a]=c},addAction:function(a,c){var b=this;this.actions[a]={};d.each(c,function(c,d){b.actions[a][c]={};b.actions[a][c].ctrl=b.form.optionControllers[c];b.actions[a][c].value=
d})},fixValueType:function(a){return a},change:function(){this.form.showDependencedOptions(this.getName());this.verifyOption()&&this.form.render()}});b.TextControl=b.OptionControl.extend({},{verifyOption:function(){if(this.settings.hasOwnProperty("required")&&1==this.settings.required){if(""===this.getValue())return this.showError(b.Vars.lang.emptyInputError.replace("%s",this.getLabel())),!1}else this.hideError();return!0}});b.NumberControl=b.OptionControl.extend({},{verifyOption:function(){var a=
this.getValue();if(!a&&(this.settings.hasOwnProperty("required")||!this.settings.required))return!0;if(!(new RegExp(/^[+-]?(\d+[.])?\d+$/)).test(a))return this.showError(b.Vars.lang.validate_digitals_only.replace("%s",this.getLabel())),!1;if(this.settings.hasOwnProperty("min")&&a<this.settings.min)return this.showError(b.Vars.lang.validate_less_min.replace("%s",this.getLabel()).replace("%d",this.settings.min)),!1;if(this.settings.hasOwnProperty("max")&&a>this.settings.max)return this.showError(b.Vars.lang.validate_greater_max.replace("%s",
this.getLabel()).replace("%d",this.settings.max)),!1;this.hideError();return!0},"input keydown":function(a,c){var b=this.getValue(),b=!isNaN(parseFloat(b))&&isFinite(b)?parseFloat(b):0;"38"==c.keyCode?this.setValue(b+1):"40"==c.keyCode&&this.setValue(b-1)}});b.TextareaControl=b.OptionControl.extend({},{setElement:function(a){this.element=a.find("textarea")}});b.CodeMirrorControl=b.TextareaControl.extend({},{init:function(a,c){this._super(a,c);this.CodeMirrorObj=CodeMirror.fromTextArea(this.element.get(0),
{lineNumbers:!0,mode:"undefined"!==typeof this.settings.mode?this.settings.mode:null})},getValue:function(){return this.CodeMirrorObj.getValue()},setValue:function(a,c){this.CodeMirrorObj.setValue(a);"undefined"!==typeof c&&c||this.element.change()}});b.CheckboxControl=b.OptionControl.extend({},{getValue:function(){return 1<this.element.length?this.element.filter(":checked").map(function(a,c){return d(c).val()}).get():this.element.is(":checked")},setValue:function(a,c){var b=this;this.element.attr("checked",
!1);d.isArray(a)?d.each(a,function(a,c){b.element.filter('[value="'+c+'"]').attr("checked",!0)}):this.element.attr("checked",a);"undefined"!==typeof c&&c||this.element.change()},fixValueType:function(a){if(this.isMultiValue)return a;switch(typeof a){case "string":return"true"===a;case "boolean":return a;default:return Boolean(a)}}});b.SelectControl=b.OptionControl.extend({},{setElement:function(a){this.element=a.find("select")}});b.RadioGroupControl=b.OptionControl.extend({},{getValue:function(){return this.element.filter(":checked").val()},
setValue:function(a,c){this.element.attr("checked",!1);this.element.filter('[value="'+a+'"]').attr("checked",!0);"undefined"!==typeof c&&c||this.element.change()}});b.RadioButtonsControl=b.RadioGroupControl.extend({},{init:function(a,c){this._super(a,c);this.element.parent().buttonset()},setValue:function(a,c){this.element.attr("checked",!1).next("label").removeClass("button-primary");this.element.filter('[value="'+a+'"]').attr("checked",!0).next("label").addClass("button-primary");"undefined"!==
typeof c&&c||this.element.change()},change:function(a,c){b.OptionControl.prototype.change.apply(this,arguments);this.element.next("label").removeClass("button-primary");this.element.filter(":checked").next("label").addClass("button-primary")}});b.ButtonGroupControl=b.OptionControl.extend({},{setElement:function(a){this.element=a.find("button")},getValue:function(){return this.element.filter(".active").val()},setValue:function(a,c){this.element.removeClass("active").filter('[value="'+a+'"]').addClass("active");
"undefined"!==typeof c&&c||this.element.change()},".button click":function(a){this.element.removeClass("active");a.addClass("active");this.change()}});b.ActionGroupControl=b.OptionControl.extend({},{getValue:function(){return""},setValue:function(a,c){"undefined"!==typeof c&&c||this.element.change()},".actions > a click":function(a){d.each(this.actions[a.attr("value")],function(a,b){b.ctrl.setValue(b.value)});this.change()}});b.AliasControl=b.OptionControl.extend({},{verifyOption:function(){var a=
!1,a=this.getValue();(new RegExp(/^[-_a-zA-Z0-9]{1,250}$/)).test(a)?a=!0:(this.showError(b.Vars.lang.aliasNotValidPattern),a=!1);return a}});b.ImageLibraryControl=b.OptionControl.extend({defaults:{id:"mpsl-media-library",multiple:!1,describe:!1,toolbar:"select",sidebar:"settings",content:"upload",router:"browse",menu:"default",searchable:!0,filterable:!1,sortable:!1,title:"tmp Title",button:{text:"tmp Text"},library:{type:"image"},contentUserSetting:!0,syncSelection:!0}},{frame:null,init:function(a,
c){this._super(a,c);this.frame=wp.media({id:"mpsl-add-image-"+this.name,multiple:!1,describe:!1,toolbar:"select",sidebar:"settings",content:"upload",router:"browse",menu:"default",searchable:!0,filterable:!1,sortable:!1,title:this.settings.label,button:{text:this.settings.select_label},library:{type:"image"},contentUserSetting:!0,syncSelection:!0});this.frame.on("open",this.proxy("onFrameOpen"));this.frame.on("select",this.proxy("onFrameSelect"));this.frame.on("close",this.proxy("onFrameClose"))},
onFrameOpen:function(){var a=this.getValue();if(""!==a){var c=this.frame.state().get("selection"),a=wp.media.attachment(a);a.fetch();c.add(a?[a]:[])}},onFrameSelect:function(){var a=this,c=this.frame.state().get("selection").models[0].attributes;wp.media.attachment(c.id).fetch().done(function(){a.setValue(c.id,!0);d.each(a.helpers,function(){this.setValue(c.url)})})},onFrameClose:function(){},".mpsl-option-library-image-btn click":function(){this.frame.open()},".mpsl-option-library-image-remove click":function(){this.setValue("",
!0);d.each(this.helpers,function(){this.setValue("")})}});b.VideoLibraryControl=b.OptionControl.extend({},{frame:null,init:function(a,c){this._super(a,c);var b=this.settings.hasOwnProperty("button_label")?this.settings.button_label:"Add Video",b={id:"mpsl-add-video-"+this.name,multiple:!1,describe:!1,toolbar:"select",sidebar:"settings",content:"upload",router:"browse",menu:"default",searchable:!0,filterable:!1,sortable:!1,title:this.settings.label,button:{text:b},library:{type:"video"},contentUserSetting:!0,
syncSelection:!0};wp.media.attachment(this.getValue()).fetch();this.frame=wp.media(b);this.frame.on("open",this.proxy("onFrameOpen"));this.frame.on("select",this.proxy("onFrameSelect"));this.frame.on("close",this.proxy("onFrameClose"))},onFrameOpen:function(){var a=this.getValue();if(""!==a){var b=this.frame.state().get("selection"),a=wp.media.attachment(a);a.fetch();b.add(a?[a]:[])}},onFrameSelect:function(){var a=this.frame.state().get("selection").models[0].attributes;wp.media.attachment(a.id).fetch();
this.setValue(a.id)},onFrameClose:function(){},".mpsl-option-library-video-btn click":function(){this.frame.open()}});b.ImageUrlControl=b.OptionControl.extend({},{".mpsl-option-image-load-btn click":function(){this.change()}});b.ShortcodeControl=b.OptionControl.extend({},{});b.HiddenControl=b.OptionControl.extend({},{});b.AlignTableControl=b.OptionControl.extend({},{table:{},init:function(a,b){this._super(a,b);this.table=a.find(".mpsl-align-table")},setElement:function(a){this.element=a},".mpsl-align-table a click":function(a){var b=
a.attr("data-hor");a=a.attr("data-vert");var d=this.childOptions.offset_x.settings["default"],f=this.childOptions.offset_y.settings["default"];this.childOptions.hor_align.setValue(b,!0);this.childOptions.vert_align.setValue(a,!0);this.childOptions.offset_x.setValue(d,!0);this.childOptions.offset_y.setValue(f,!0);this.selectBullet(b,a);this.change()},getValue:function(){return{hor:this.childOptions.hor_align.getValue(),vert:this.childOptions.vert_align.getValue()}},setValue:function(a,b){this.selectBullet(a.hor,
a.vert);"undefined"!==typeof b&&b||this.element.change()},selectBullet:function(a,b){this.table.find("a.selected").removeClass("selected").end().find('a[data-hor="'+a+'"][data-vert="'+b+'"]').addClass("selected")}});b.DatePicker=b.OptionControl.extend({},{init:function(a,b){this._super(a,b);this.element.datepicker({dateFormat:"dd-mm-yy 00:00"})},verifyOption:function(){var a=this.getValue();if(""===a)return!0;a=a.match(new RegExp(/^(\d{2})-(\d{2})-(\d{4})\s(\d{2}):(\d{2})$/));return null===a?(this.showError(b.Vars.lang.validate_invalid_date_format.replace("%s",
this.getLabel())),!1):1>a[1]||31<a[1]?(this.showError(b.Vars.lang.validate_invalid_day.replace("%s",this.getLabel()).replace("%day",a[1])),!1):1>a[2]||12<a[2]?(this.showError(b.Vars.lang.validate_invalid_month.replace("%s",this.getLabel()).replace("%month",a[2])),!1):1970>a[3]||2037<a[3]?(this.showError(b.Vars.lang.validate_invalid_year.replace("%s",this.getLabel()).replace("%year",a[3]).replace("%minYear",1970).replace("%maxYear",2037)),!1):0>a[4]||23<a[4]?(this.showError(b.Vars.lang.validate_invalid_hour.replace("%s",
this.getLabel()).replace("%hour",a[4])),!1):0>a[5]||59<a[5]?(this.showError(b.Vars.lang.validate_invalid_minute.replace("%s",this.getLabel()).replace("%minute",a[5])),!1):!0}})})(jQuery,MPSL);
